import './module/input.js'
import './module/textarea.js'
import './module/checkbox.js'
import './module/radio.js'
import './module/slider.js'
import './module/adaptive.js'
import './module/ajax-form.js'
